# file: hostname/tasks/main.yml

- name: Hostname | Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{{ ansible_host }}"

- name: Hostname | Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{{ ansible_host }}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Hostname | Update the IPv4 hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{ ansible_host }}{{'\t'}}localhost"
    state: present

- name: Hostname | Update the IPv6 hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1{{'\t\t'}}{{ ansible_host }}{{'\t'}}localhost ip6-localhost ip6-loopback"
    state: present
