# file: hostname/tasks/main.yml

- name: Hostname | Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{{ inventory_hostname }}"

- name: Hostname | Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{{ inventory_hostname }}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Hostname | Update the IPv4 loopback hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{ inventory_hostname }}{{'\t'}}localhost"
    state: present

- name: Hostname | Update the IPv4 Public IP hostname (pt. 4) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }}{{'\t'}}{{ inventory_hostname }}"
    state: present

- name: Hostname | Update the IPv6 hostname (pt. 5) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1{{'\t\t'}}{{ inventory_hostname }}{{'\t'}}localhost ip6-localhost ip6-loopback"
    state: present
    
